### ISSUE TITLE
MemoryError (timestamp issues)

### ISSUE THREAD

**Issue by davidfokkema** [HiSPARC/pysparc#11]
```python
Traceback (most recent call last):
  File "/opt/pysparc/scripts/test_hv.py", line 134, in <module>
    app.run()
  File "/opt/pysparc/scripts/test_hv.py", line 75, in run
    stew.add_one_second_message(msg)
  File "/opt/pysparc/pysparc/events.py", line 57, in add_one_second_message
    for t in range(self._latest_timestamp + 1, timestamp):
MemoryError
```

Probably because the range is inverted? Strange that Python would give a MemoryError instead of a ValueError or something like that. It is a bit strange however, since:

```python
>>> range(10, 15)
[10, 11, 12, 13, 14]
>>> range(15, 10)
[]
```

**Comment by davidfokkema** [comment]
Well, this was months ago. Refactoring the one-second msg handling probably fixed the bug. We currently have three systems running without problems for an extended period of time (weeks). The only problem I encountered in the past weeks: problems loading off events to the datastore. And then memory starts to slowly fill up... Nothing to do with this, so I'm closing this bug.
